[paths]
chara_list = "references/characters_pvp.toml"
charge_speed = "references/characters_pvp.toml"
alias_mapping = "sub-skills/alias_mapping/alias_mapping_pvp.toml"
matches = "data/matches.toml"
match_schema = "sub-skills/match_recorder/schema/match_schema.toml"

[charge]
phases = ["2RL", "50SMG", "3RL"]
